-- MySQL Script generated by MySQL Workbench
-- 11/28/15 20:16:09
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema pocketmedic
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pocketmedic
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pocketmedic` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `pocketmedic` ;

-- -----------------------------------------------------
-- Table `pocketmedic`.`PAISES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`PAISES` (
  `id_pais` VARCHAR(3) NOT NULL COMMENT '',
  `nombre_pais` VARCHAR(60) NOT NULL COMMENT '',
  PRIMARY KEY (`id_pais`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`DEPARTAMENTOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`DEPARTAMENTOS` (
  `id_departamento` INT NOT NULL COMMENT '',
  `nombre_departamento` VARCHAR(60) NOT NULL COMMENT '',
  `id_pais` VARCHAR(3) NOT NULL COMMENT '',
  PRIMARY KEY (`id_departamento`)  COMMENT '',
  INDEX `fk_DEPARTAMENTOS_PAISES1_idx` (`id_pais` ASC)  COMMENT '',
  CONSTRAINT `fk_DEPARTAMENTOS_PAISES1`
    FOREIGN KEY (`id_pais`)
    REFERENCES `pocketmedic`.`PAISES` (`id_pais`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`CIUDADES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`CIUDADES` (
  `id_ciudad` INT NOT NULL COMMENT '',
  `nombre_ciudad` VARCHAR(60) NOT NULL COMMENT '',
  `id_departamento` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_ciudad`, `id_departamento`)  COMMENT '',
  INDEX `fk_CIUDADES_DEPARTAMENTOS1_idx` (`id_departamento` ASC)  COMMENT '',
  CONSTRAINT `fk_CIUDADES_DEPARTAMENTOS1`
    FOREIGN KEY (`id_departamento`)
    REFERENCES `pocketmedic`.`DEPARTAMENTOS` (`id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`ROLES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`ROLES` (
  `id_rol` VARCHAR(10) NOT NULL COMMENT '',
  `nombre_rol` VARCHAR(20) NOT NULL COMMENT '',
  PRIMARY KEY (`id_rol`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`EMPRESAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`EMPRESAS` (
  `id_empresa` INT NOT NULL COMMENT '',
  `nit` VARCHAR(30) NULL COMMENT '',
  `nombre` VARCHAR(70) NULL COMMENT '',
  `tipo_de_servicio` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_empresa`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`USUARIOS` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `nombres` VARCHAR(40) NULL COMMENT '',
  `apellidos` VARCHAR(40) NULL COMMENT '',
  `telefono` VARCHAR(16) NULL COMMENT '',
  `direccion` VARCHAR(100) NULL COMMENT '',
  `email` VARCHAR(100) NULL COMMENT '',
  `fecha_nac` DATE NULL COMMENT '',
  `sexo` CHAR NULL COMMENT '',
  `documento` VARCHAR(45) NULL COMMENT '',
  `password` VARCHAR(64) NULL COMMENT '',
  `avatar` VARCHAR(500) NULL COMMENT '',
  `tarjeta_profesional` VARCHAR(45) NULL COMMENT '',
  `id_ciudad` INT NULL COMMENT '',
  `id_departamento` INT NULL COMMENT '',
  `id_rol` VARCHAR(10) NULL COMMENT '',
  `id_empresa` INT NULL COMMENT '',
  PRIMARY KEY (`id_usuario`)  COMMENT '',
  INDEX `fk_USUARIOS_CIUDADES1_idx` (`id_ciudad` ASC, `id_departamento` ASC)  COMMENT '',
  INDEX `fk_USUARIOS_ROLES1_idx` (`id_rol` ASC)  COMMENT '',
  INDEX `fk_USUARIOS_EMPRESAS1_idx` (`id_empresa` ASC)  COMMENT '',
  CONSTRAINT `fk_USUARIOS_CIUDADES1`
    FOREIGN KEY (`id_ciudad` , `id_departamento`)
    REFERENCES `pocketmedic`.`CIUDADES` (`id_ciudad` , `id_departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_ROLES1`
    FOREIGN KEY (`id_rol`)
    REFERENCES `pocketmedic`.`ROLES` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USUARIOS_EMPRESAS1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `pocketmedic`.`EMPRESAS` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`TITULOS_Y_CERTIFICADOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`TITULOS_Y_CERTIFICADOS` (
  `id_profesiones` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `titulos` VARCHAR(60) NOT NULL COMMENT '',
  PRIMARY KEY (`id_profesiones`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`PROFESIONES_USUARIOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`PROFESIONES_USUARIOS` (
  `id_profesion_usuario` INT NOT NULL COMMENT '',
  `id_profesiones` INT NOT NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_profesiones`, `id_usuario`, `id_profesion_usuario`)  COMMENT '',
  INDEX `fk_PROFESIONES_has_USUARIOS_USUARIOS1_idx` (`id_usuario` ASC)  COMMENT '',
  INDEX `fk_PROFESIONES_has_USUARIOS_PROFESIONES1_idx` (`id_profesiones` ASC)  COMMENT '',
  CONSTRAINT `fk_PROFESIONES_has_USUARIOS_PROFESIONES1`
    FOREIGN KEY (`id_profesiones`)
    REFERENCES `pocketmedic`.`TITULOS_Y_CERTIFICADOS` (`id_profesiones`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PROFESIONES_has_USUARIOS_USUARIOS1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `pocketmedic`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`CONSULTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`CONSULTAS` (
  `id_consultas` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  `publico` TINYINT(1) NULL COMMENT '',
  `url_image` VARCHAR(500) NULL COMMENT '',
  `usuario` INT NOT NULL COMMENT '',
  `medico` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_consultas`)  COMMENT '',
  INDEX `fk_CONSULTAS_USUARIOS1_idx` (`usuario` ASC)  COMMENT '',
  INDEX `fk_CONSULTAS_USUARIOS2_idx` (`medico` ASC)  COMMENT '',
  CONSTRAINT `fk_CONSULTAS_USUARIOS1`
    FOREIGN KEY (`usuario`)
    REFERENCES `pocketmedic`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONSULTAS_USUARIOS2`
    FOREIGN KEY (`medico`)
    REFERENCES `pocketmedic`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`RESPUESTAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`RESPUESTAS` (
  `id_respuestas` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(500) NULL COMMENT '',
  `id_consultas` INT NOT NULL COMMENT '',
  `id_usuario` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_respuestas`)  COMMENT '',
  INDEX `fk_RESPUESTAS_CONSULTAS1_idx` (`id_consultas` ASC)  COMMENT '',
  INDEX `fk_RESPUESTAS_USUARIOS1_idx` (`id_usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_RESPUESTAS_CONSULTAS1`
    FOREIGN KEY (`id_consultas`)
    REFERENCES `pocketmedic`.`CONSULTAS` (`id_consultas`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RESPUESTAS_USUARIOS1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `pocketmedic`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`CITAS_MEDICAS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`CITAS_MEDICAS` (
  `id_cita` INT NOT NULL COMMENT '',
  `fecha_cita` DATE NULL COMMENT '',
  `usuario` INT NOT NULL COMMENT '',
  `medico` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_cita`)  COMMENT '',
  INDEX `fk_CITAS_MEDICAS_USUARIOS1_idx` (`usuario` ASC)  COMMENT '',
  INDEX `fk_CITAS_MEDICAS_USUARIOS2_idx` (`medico` ASC)  COMMENT '',
  CONSTRAINT `fk_CITAS_MEDICAS_USUARIOS1`
    FOREIGN KEY (`usuario`)
    REFERENCES `pocketmedic`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CITAS_MEDICAS_USUARIOS2`
    FOREIGN KEY (`medico`)
    REFERENCES `pocketmedic`.`USUARIOS` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`TIPOS_DE_PAGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`TIPOS_DE_PAGOS` (
  `id_tipo_pago` INT NOT NULL COMMENT '',
  `descripcion` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id_tipo_pago`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`PAGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`PAGOS` (
  `id_pagos` INT NOT NULL COMMENT '',
  `estado` TINYINT(1) NULL COMMENT '',
  `fecha` DATE NULL COMMENT '',
  `id_tipo_pago` INT NULL COMMENT '',
  PRIMARY KEY (`id_pagos`)  COMMENT '',
  INDEX `fk_PAGOS_TIPOS_DE_PAGOS1_idx` (`id_tipo_pago` ASC)  COMMENT '',
  CONSTRAINT `fk_PAGOS_TIPOS_DE_PAGOS1`
    FOREIGN KEY (`id_tipo_pago`)
    REFERENCES `pocketmedic`.`TIPOS_DE_PAGOS` (`id_tipo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `pocketmedic`.`EMPRESAS_PAGOS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pocketmedic`.`EMPRESAS_PAGOS` (
  `id_empresa_pago` INT NOT NULL COMMENT '',
  `id_empresa` INT NOT NULL COMMENT '',
  `id_pagos` INT NOT NULL COMMENT '',
  PRIMARY KEY (`id_empresa_pago`, `id_empresa`, `id_pagos`)  COMMENT '',
  INDEX `fk_EMPRESAS_has_PAGOS_PAGOS1_idx` (`id_pagos` ASC)  COMMENT '',
  INDEX `fk_EMPRESAS_has_PAGOS_EMPRESAS1_idx` (`id_empresa` ASC)  COMMENT '',
  CONSTRAINT `fk_EMPRESAS_has_PAGOS_EMPRESAS1`
    FOREIGN KEY (`id_empresa`)
    REFERENCES `pocketmedic`.`EMPRESAS` (`id_empresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPRESAS_has_PAGOS_PAGOS1`
    FOREIGN KEY (`id_pagos`)
    REFERENCES `pocketmedic`.`PAGOS` (`id_pagos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
